export const SampleMovie = {
  adult: false,
  backdrop_path: "/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg",
  belongs_to_collection: {
    id: 10,
    name: "Star Wars Collection",
    poster_path: "/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg",
    backdrop_path: "/d8duYyyC9J5T825Hg7grmaabfxQ.jpg",
  },
  budget: 200000000,
  credits: {
    cast: [
      {
        adult: false,
        gender: 2,
        id: 2,
        known_for_department: "Acting",
        name: "Mark Hamill",
        original_name: "Mark Hamill",
        popularity: 1.9723,
        profile_path: "/2ZulC2Ccq1yv3pemusks6Zlfy2s.jpg",
        cast_id: 14,
        character: "Luke Skywalker / Dobbu Scay (voice)",
        credit_id: "5679cdd4c3a3685bbf000206",
        order: 0,
      },
      {
        adult: false,
        gender: 1,
        id: 4,
        known_for_department: "Acting",
        name: "Carrie Fisher",
        original_name: "Carrie Fisher",
        popularity: 1.3083,
        profile_path: "/awb4UqzT6meD3JiQlraIzAqcRtH.jpg",
        cast_id: 15,
        character: "Leia Organa",
        credit_id: "567aa394c3a3685bdf00266a",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 1023139,
        known_for_department: "Acting",
        name: "Adam Driver",
        original_name: "Adam Driver",
        popularity: 1.2058,
        profile_path: "/rsjwgpV2OukxOJ9HEiEyf4qu1vR.jpg",
        cast_id: 13,
        character: "Kylo Ren",
        credit_id: "5679cdbd92514106f50001e9",
        order: 2,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 3402805,
        known_for_department: "Production",
        name: "Maroje Žanetić",
        original_name: "Maroje Žanetić",
        popularity: 0.0538,
        profile_path: null,
        credit_id: "62719747245dbe3381b0070a",
        department: "Production",
        job: "Location Manager",
      },
      {
        adult: false,
        gender: 2,
        id: 1,
        known_for_department: "Directing",
        name: "George Lucas",
        original_name: "George Lucas",
        popularity: 1.1034,
        profile_path: "/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg",
        credit_id: "52fe4c709251416c7511a87b",
        department: "Writing",
        job: "Characters",
      },
      {
        adult: false,
        gender: 0,
        id: 2151819,
        known_for_department: "Crew",
        name: "Caridad Angus",
        original_name: "Caridad Angus",
        popularity: 0.0382,
        profile_path: null,
        credit_id: "628592cffa78cd2dc5bcdae0",
        department: "Crew",
        job: "Stand In",
      },
    ],
  },
  genre_ids: [28, 12, 14, 878],
  genres: [
    {
      id: 14,
      name: "Fantasy",
    },
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 878,
      name: "Science Fiction",
    },
    {
      id: 28,
      name: "Action",
    },
  ],
  homepage:
    "https://www.starwars.com/films/star-wars-episode-viii-the-last-jedi",
  id: 181808,
  imdb_id: "tt2527336",
  original_language: "en",
  original_title: "Star Wars: The Last Jedi",
  overview:
    "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
  popularity: 44.208,
  poster_path: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
  production_companies: [
    {
      id: 1,
      logo_path: "/o86DbpburjxrqAzEDhXZcyE8pDb.png",
      name: "Lucasfilm",
      origin_country: "US",
    },
    {
      id: 11092,
      logo_path: null,
      name: "Ram Bergman Productions",
      origin_country: "US",
    },
    {
      id: 2,
      logo_path: "/wdrCwmRnLFJhEoH8GSfymY85KHT.png",
      name: "Walt Disney Pictures",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2017-12-13",
  revenue: 1332459537,
  runtime: 152,
  similar: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [28, 27, 14],
        id: 1371510,
        original_language: "en",
        original_title: "Darkside Witches II",
        overview:
          "Father Gabriel's team were slaughtered l by Pazuzu and its demons, the village is cursed, and Gabriel himself captured in the underworld. Lucrezia, the strongest of the black witches, is on her way to Rome to destroy the Vatican.",
        popularity: 0.7507,
        poster_path: "/nC5el7q2MPFIdajCfywMnEVXKv0.jpg",
        release_date: "",
        title: "Darkside Witches II",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/iaNoLnnpQb5SNxGc4bkQmdCvEdG.jpg",
        genre_ids: [16, 10751, 35, 14, 12],
        id: 809,
        original_language: "en",
        original_title: "Shrek 2",
        overview:
          "Shrek, Fiona, and Donkey set off to Far, Far Away to meet Fiona's mother and father, the Queen and King. But not everyone is happily ever after. Shrek and the King find it difficult to get along, and there's tension in the marriage. The Fairy Godmother discovers that Fiona has married Shrek instead of her son Prince Charming and plots to destroy their marriage.",
        popularity: 20.0681,
        poster_path: "/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg",
        release_date: "2004-05-19",
        title: "Shrek 2",
        video: false,
        vote_average: 7.3,
        vote_count: 12865,
      },
      {
        adult: false,
        backdrop_path: "/qSNz1G1Ts8fFw6v4Vae4aMAjcY7.jpg",
        genre_ids: [14, 12, 16, 35, 10751],
        id: 810,
        original_language: "en",
        original_title: "Shrek the Third",
        overview:
          "The King of Far Far Away has died and Shrek and Fiona are to become King & Queen. However, Shrek wants to return to his cozy swamp and live in peace and quiet, so when he finds out there is another heir to the throne, they set off to bring him back to rule the kingdom.",
        popularity: 17.1519,
        poster_path: "/n4SexGGQzI26E269tfpa80MZaGV.jpg",
        release_date: "2007-05-17",
        title: "Shrek the Third",
        video: false,
        vote_average: 6.297,
        vote_count: 9381,
      },
    ],
    total_pages: 1,
    total_results: 3,
  },
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Darkness rises... and light to meet it",
  title: "Star Wars: The Last Jedi",
  video: false,
  vote_average: 7,
  vote_count: 9692,
};

export const SamplePerson = {
  adult: false,
  also_known_as: [
    "Ice Cube Nwa",
    "O'Shea Jackson",
    "Westside Connection",
    "N.W.A.",
    "NWA",
    "ო’ში ჯექსონი (Ice Cube)",
  ],
  biography:
    "O'Shea Jackson Sr., better known by his stage name Ice Cube, (born June 15, 1969) is an American rapper, record producer, and filmmaker. He began his career as a member of the hip-hop group C.I.A. and later joined N.W.A. He is known for his roles in the films “Boyz n the Hood,” “Friday,” and the “Jump Street” series.",
  birthday: "1969-06-15",
  deathday: null,
  gender: 2,
  homepage: "https://icecube.com/",
  id: 9778,
  imdb_id: "nm0001084",
  known_for_department: "Acting",
  movie_credits: {
    cast: [
      {
        adult: false,
        backdrop_path: "/6N2aaG46UYcgef7Vg8aUKp59poe.jpg",
        genre_ids: [80, 18],
        id: 650,
        original_language: "en",
        original_title: "Boyz n the Hood",
        overview:
          "In the middle of the Los Angeles ghetto, drugs, robberies and shootings dominate everyday life. During these times, Furious tries to raise his son Tre to be a decent person. Tre's friends, on the other hand, have little regard for the law and drag the entire neighborhood into a street war...",
        popularity: 6.5597,
        poster_path: "/v4ox4aSCNT5vyLXl4Q71JiWwCXW.jpg",
        release_date: "1991-07-12",
        title: "Boyz n the Hood",
        video: false,
        vote_average: 7.631,
        vote_count: 2107,
        character: "Doughboy",
        credit_id: "52fe4264c3a36847f801aebd",
        order: 2,
      },
      {
        adult: false,
        backdrop_path: "/xVfjgAzvdmHdW25ZUG3nMKKmauX.jpg",
        genre_ids: [10751, 35],
        id: 10172,
        original_language: "en",
        original_title: "Are We Done Yet?",
        overview:
          "Newlyweds Nick and Suzanne decide to move to the suburbs to provide a better life for their two kids. But their idea of a dream home is disturbed by a contractor with a bizarre approach to business.",
        popularity: 2.345,
        poster_path: "/uZ9NZh4zB80phMxo5PucFyWagjG.jpg",
        release_date: "2007-04-04",
        title: "Are We Done Yet?",
        video: false,
        vote_average: 5.8,
        vote_count: 643,
        character: "Nick Persons",
        credit_id: "52fe433a9251416c750086b1",
        order: 0,
      },
      {
        adult: false,
        backdrop_path: "/1loG5dSesKgwakjOET0Ll27jKgI.jpg",
        genre_ids: [28, 27, 878],
        id: 10016,
        original_language: "en",
        original_title: "Ghosts of Mars",
        overview:
          "In 2176, a Martian police unit is sent to pick up a highly dangerous criminal at a remote mining post. Upon arrival, the cops find the post deserted and something far more dangerous than any criminal — the original inhabitants of Mars, hellbent on getting their planet back.",
        popularity: 3.3589,
        poster_path: "/i2zztssCIbahGES1fdfWFmDXian.jpg",
        release_date: "2001-08-24",
        title: "Ghosts of Mars",
        video: false,
        vote_average: 5.149,
        vote_count: 1160,
        character: "James 'Desolation' Williams",
        credit_id: "52fe43089251416c75000d75",
        order: 1,
      },
    ],
    crew: [
      {
        adult: false,
        backdrop_path: "/xVfjgAzvdmHdW25ZUG3nMKKmauX.jpg",
        genre_ids: [10751, 35],
        id: 10172,
        original_language: "en",
        original_title: "Are We Done Yet?",
        overview:
          "Newlyweds Nick and Suzanne decide to move to the suburbs to provide a better life for their two kids. But their idea of a dream home is disturbed by a contractor with a bizarre approach to business.",
        popularity: 2.345,
        poster_path: "/uZ9NZh4zB80phMxo5PucFyWagjG.jpg",
        release_date: "2007-04-04",
        title: "Are We Done Yet?",
        video: false,
        vote_average: 5.8,
        vote_count: 643,
        credit_id: "52fe433a9251416c750086cf",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        backdrop_path: "/p5ZW0xCRXO8vf1byKzSJzIOj6hm.jpg",
        genre_ids: [10751, 12, 35, 10749],
        id: 11637,
        original_language: "en",
        original_title: "Are We There Yet?",
        overview:
          "The fledgling romance between Nick, a playboy bachelor, and Suzanne, a divorced mother of two, is threatened by a particularly harrowing New Years Eve. When Suzanne's work keeps her in Vancouver for the holiday, Nick offers to bring her kids to the city from Portland, Oregon. The kids, who have never liked any of the men their mom dates, are determined to turn the trip into a nightmare for Nick.",
        popularity: 3.9781,
        poster_path: "/guDkMD4wrZ1BGUO7DFFBVzaiGij.jpg",
        release_date: "2005-01-20",
        title: "Are We There Yet?",
        video: false,
        vote_average: 5.662,
        vote_count: 1007,
        credit_id: "52fe446e9251416c750346c5",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        backdrop_path: "/jsbQxz3dMWq5Nv7jSasYXyUylCU.jpg",
        genre_ids: [35],
        id: 25186,
        original_language: "en",
        original_title: "Janky Promoters",
        overview:
          "Two shady concert promoters get into hot water when their chance to book a superstar rapper goes awry.",
        popularity: 0.6906,
        poster_path: "/sQTn0iUDsfwSLOznzOzfDhC3J8I.jpg",
        release_date: "2009-10-16",
        title: "Janky Promoters",
        video: false,
        vote_average: 5.583,
        vote_count: 36,
        credit_id: "52fe44bcc3a368484e033f5d",
        department: "Writing",
        job: "Writer",
      },
    ],
  },
  name: "Ice Cube",
  place_of_birth: "Los Angeles, California, USA",
  popularity: 1.8138,
  profile_path: "/ymR7Yll7HjL6i6Z3pt435hYi91T.jpg",
  tv_credits: {
    cast: [
      {
        adult: false,
        backdrop_path: "/3jMCaxKK4r5A5gu196dCCrk5d6X.jpg",
        genre_ids: [35, 10767],
        id: 562,
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Ellen DeGeneres Show",
        overview:
          "The Ellen DeGeneres Show, often shortened to just Ellen, is an American television talk show hosted by comedian/actress Ellen DeGeneres.",
        popularity: 10.3562,
        poster_path: "/PhUYIGUUk1RzWq2Aw3TqH65McE.jpg",
        first_air_date: "2003-09-08",
        name: "The Ellen DeGeneres Show",
        vote_average: 5.669,
        vote_count: 163,
        character: "Self",
        credit_id: "525386ae19c295794020fd83",
        episode_count: 2,
        first_credit_air_date: "2005-01-25",
      },
      {
        adult: false,
        backdrop_path: "/8gn8kABdGu32PXf9xWT3f0PCS60.jpg",
        genre_ids: [35],
        id: 1693,
        origin_country: ["US"],
        original_language: "en",
        original_name: "The Bernie Mac Show",
        overview:
          "The Bernie Mac Show is an American sitcom that aired on Fox for five seasons from November 14, 2001 to April 14, 2006. The series featured comic actor Bernie Mac and his wife Wanda raising his sister's three kids: Jordan, Bryana, and Vanessa.",
        popularity: 8.601,
        poster_path: "/auTnAsA5USO1901qti1mxbUIVoE.jpg",
        first_air_date: "2001-11-14",
        name: "The Bernie Mac Show",
        vote_average: 6.452,
        vote_count: 63,
        character: "Ice Cube",
        credit_id: "5257108e760ee3776a0bb0a8",
        episode_count: 1,
        first_credit_air_date: "2002-09-25",
      },
      {
        adult: false,
        backdrop_path: "/upD2G9Z7W07w47c7B8ZqLqbTDc5.jpg",
        genre_ids: [10767],
        id: 1900,
        origin_country: ["US"],
        original_language: "en",
        original_name: "LIVE with Kelly and Mark",
        overview:
          "A morning talk show with A-list celebrity guests, top-notch performances and one-of-a-kind segments that are unrivaled on daytime television, plus spontaneous, hilarious and unpredictable talk.",
        popularity: 12.3414,
        poster_path: "/hBkyypWN3EcOzkozatiCm5VeaG.jpg",
        first_air_date: "1988-09-05",
        name: "LIVE with Kelly and Mark",
        vote_average: 5.5,
        vote_count: 47,
        character: "",
        credit_id: "52571a5719c29571140c6556",
        episode_count: 1,
        first_credit_air_date: "2008-01-09",
      },
    ],
    crew: [
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [35, 18],
        id: 9861,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Barbershop",
        overview:
          "Calvin Palmer is the owner of a barbershop on the Southside of Chicago. Reluctantly inheriting the neighborhood establishment and popular hangout from his father, he juggles his responsibilities to his clients, his family, and his community as a cast of unique characters regularly bring their hopes, dreams and problems with them into the shop.",
        popularity: 0.9334,
        poster_path: "/8PazY5yDKkZh0VMKdmVOPMJNhHw.jpg",
        first_air_date: "2005-08-14",
        name: "Barbershop",
        vote_average: 7.3,
        vote_count: 6,
        credit_id: "5257f84519c29531db2d05af",
        department: "Production",
        episode_count: 10,
        first_credit_air_date: "2005-08-14",
        job: "Producer",
      },
      {
        adult: false,
        backdrop_path: "/97Bw1z2E4uUbhogcwldBLs3ZmCf.jpg",
        genre_ids: [],
        id: 10890,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Black. White.",
        overview:
          "Black. White. was a reality television show on FX. It premiered on Wednesday March 8, 2006 at 10 p.m. Eastern. The series followed two families of three, one white, and the other black. Through studio-quality make-up, the two families—the Wurgels and the Sparks—traded races and experienced what life is like in the other family's shoes. The show was produced and created by Ice Cube, R. J. Cutler and the show's theme song was \"Race Card\", performed by Ice Cube and produced by Warren G. The series had six episodes.",
        popularity: 0.699,
        poster_path: "/usnxEOeBFjHwGE2kVZ4OXn1tEzD.jpg",
        first_air_date: "2006-03-08",
        name: "Black. White.",
        vote_average: 0,
        vote_count: 0,
        credit_id: "525808a019c29531db3d82f9",
        department: "Production",
        episode_count: 6,
        first_credit_air_date: "2006-03-08",
        job: "Producer",
      },
      {
        adult: false,
        backdrop_path: "/iCDs2rHzB68TmpHQ9Xk4uaNzP7f.jpg",
        genre_ids: [35],
        id: 36473,
        origin_country: ["US", "CA"],
        original_language: "en",
        original_name: "Are We There Yet?",
        overview:
          "Are We There Yet? opens where the popular film of the same name left off, with Nick and Suzanne newly married. After six months, their family is beginning to show growing pains, from the complexities of life as newlyweds to weathering the storm of teenage children. Work makes life all the more complicated. Former athlete Nick has sold his sports paraphernalia store and now works in information technology. Party planner Suzanne also has a hectic professional schedule.",
        popularity: 1.819,
        poster_path: "/pDhGyrMlgrM5GKtPaJINP3Xg1kr.jpg",
        first_air_date: "2010-06-02",
        name: "Are We There Yet?",
        vote_average: 6.5,
        vote_count: 30,
        credit_id: "5258e4c8760ee34661806363",
        department: "Production",
        episode_count: 50,
        first_credit_air_date: "2010-05-04",
        job: "Producer",
      },
    ],
  },
};

export const SampleTvShow = {
  adult: false,
  backdrop_path: "/qg8Gv2w0dDL8cMsG2QO2hWp58wy.jpg",
  credits: {
    cast: [
      {
        adult: false,
        gender: 1,
        id: 974169,
        known_for_department: "Acting",
        name: "Jenna Ortega",
        original_name: "Jenna Ortega",
        popularity: 11.9202,
        profile_path: "/cV4x7jNmsGLdKZn5I6xVF3Ltnmg.jpg",
        character: "Wednesday Addams",
        credit_id: "68979464e171af0589e24616",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 884,
        known_for_department: "Acting",
        name: "Steve Buscemi",
        original_name: "Steve Buscemi",
        popularity: 3.8473,
        profile_path: "/lQKdHMxfYcCBOvwRKBAxPZVNtkg.jpg",
        character: "Barry Dort",
        credit_id: "68927083863455aa96dbf9e3",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 1911865,
        known_for_department: "Acting",
        name: "Hunter Doohan",
        original_name: "Hunter Doohan",
        popularity: 2.2723,
        profile_path: "/ihno5ut6ha8TaubQFgl5Ozco2K1.jpg",
        character: "Tyler Galpin",
        credit_id: "637e4015a410c800c8839f20",
        order: 5,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 0,
        id: 5212070,
        known_for_department: "Crew",
        name: "Chloe O'Reilly",
        original_name: "Chloe O'Reilly",
        popularity: 0.0552,
        profile_path: null,
        credit_id: "679a9d234448da3d2abd6ec7",
        department: "Directing",
        job: "Assistant Director Trainee",
      },
      {
        adult: false,
        gender: 2,
        id: 1403739,
        known_for_department: "Editing",
        name: "Nick Iannelli",
        original_name: "Nick Iannelli",
        popularity: 0.0495,
        profile_path: null,
        credit_id: "6899209483e4a8e3fc5d128f",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 4125331,
        known_for_department: "Production",
        name: "Natalie Testa",
        original_name: "Natalie Testa",
        popularity: 0.1281,
        profile_path: null,
        credit_id: "689920a907456e824e8daa5f",
        department: "Production",
        job: "Co-Producer",
      },
    ],
  },
  created_by: [
    {
      id: 18923,
      credit_id: "602e00776743fa003ce65015",
      name: "Miles Millar",
      original_name: "Miles Millar",
      gender: 2,
      profile_path: "/4phggQUKYg2WMMEy4JW8y6pKEVS.jpg",
    },
    {
      id: 18924,
      credit_id: "602e0072d55697003f5a8765",
      name: "Alfred Gough",
      original_name: "Alfred Gough",
      gender: 2,
      profile_path: "/wZV1hProzjw9oR9HtjILDMn2K6A.jpg",
    },
  ],
  episode_run_time: [],
  first_air_date: "2022-11-23",
  genre_ids: [10765, 9648, 35],
  genres: [
    { id: 10765, name: "Sci-Fi & Fantasy" },
    { id: 9648, name: "Mystery" },
    { id: 35, name: "Comedy" },
  ],
  homepage: "https://www.netflix.com/title/81231974",
  id: 119051,
  in_production: true,
  languages: ["en"],
  last_air_date: "2025-08-06",
  last_episode_to_air: {
    id: 6165595,
    name: "If These Woes Could Talk",
    overview:
      "It's an Addams family investigation as Fester and Thing commit themselves to Wednesday's case. Trying to conceal one secret, Bianca stumbles on another.",
    vote_average: 8.1,
    vote_count: 32,
    air_date: "2025-08-06",
    episode_number: 4,
    episode_type: "mid_season",
    production_code: "",
    runtime: 60,
    season_number: 2,
    show_id: 119051,
    still_path: "/irw76zkymiXrrAyC1ftq8Jomsuh.jpg",
  },
  name: "Wednesday",
  next_episode_to_air: {
    id: 6165596,
    name: "Episode 5",
    overview: "",
    vote_average: 0.0,
    vote_count: 0,
    air_date: "2025-09-03",
    episode_number: 5,
    episode_type: "standard",
    production_code: "",
    runtime: null,
    season_number: 2,
    show_id: 119051,
    still_path: null,
  },
  networks: [
    {
      id: 213,
      logo_path: "/wwemzKWzjKYJFfCeiB57q3r4Bcm.png",
      name: "Netflix",
      origin_country: "",
    },
  ],
  number_of_episodes: 16,
  number_of_seasons: 2,
  origin_country: ["US"],
  original_language: "en",
  original_name: "Wednesday",
  overview:
    "Smart, sarcastic and a little dead inside, Wednesday Addams investigates twisted mysteries while making new friends — and foes — at Nevermore Academy.",
  popularity: 360.4297,
  poster_path: "/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg",
  production_companies: [
    {
      id: 2230,
      logo_path: "/igOjospzsKQIbpuFCGhoN5F9icS.png",
      name: "MGM Television",
      origin_country: "US",
    },
    {
      id: 20356,
      logo_path: "/awFYFsOyoG3VttUmWvnhgZgXxxh.png",
      name: "Millar Gough Ink",
      origin_country: "US",
    },
    {
      id: 186866,
      logo_path: "/crmJkiAcLftaxF3GoQvRHPs7gyv.png",
      name: "Toluca Pictures",
      origin_country: "US",
    },
    {
      id: 8601,
      logo_path: "/kqubCH3sfBAk4znUj7hjqv8ffgi.png",
      name: "Tim Burton Productions",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  seasons: [
    {
      air_date: "2022-11-23",
      episode_count: 8,
      id: 182137,
      name: "Season 1",
      overview: "",
      poster_path: "/v9fNsN3WNXObKJjBWkiKMuT3XoR.jpg",
      season_number: 1,
      vote_average: 8.5,
    },
    {
      air_date: "2025-08-06",
      episode_count: 8,
      id: 345672,
      name: "Season 2",
      overview: "",
      poster_path: "/aamw6JjKwTy6bdviyIcFKekSD6x.jpg",
      season_number: 2,
      vote_average: 7.8,
    },
  ],
  similar: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/b73DCbaqYICq3yUbBe5vxtbXjTX.jpg",
        genre_ids: [10765, 18, 10751],
        id: 2243,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Touched by an Angel",
        overview:
          "Monica, an angel, is tasked with bringing guidance and messages from God to various people who are at a crossroads in their lives.",
        popularity: 11.607,
        poster_path: "/jiSv0xNx6MGhAFfv05Ov7DgDELJ.jpg",
        first_air_date: "1994-09-21",
        name: "Touched by an Angel",
        vote_average: 7.2,
        vote_count: 174,
      },
    ],
    total_pages: 1,
    total_results: 1,
  },
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Returning Series",
  tagline: "The wait has been torture.",
  type: "Scripted",
  vote_average: 8.402,
  vote_count: 9504,
};
