export const SampleMovie = {
  adult: false,
  backdrop_path: "/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg",
  belongs_to_collection: {
    id: 10,
    name: "Star Wars Collection",
    poster_path: "/iTQHKziZy9pAAY4hHEDCGPaOvFC.jpg",
    backdrop_path: "/d8duYyyC9J5T825Hg7grmaabfxQ.jpg",
  },
  budget: 200000000,
  credits: {
    cast: [
      {
        adult: false,
        gender: 2,
        id: 2,
        known_for_department: "Acting",
        name: "Mark Hamill",
        original_name: "Mark Hamill",
        popularity: 1.9723,
        profile_path: "/2ZulC2Ccq1yv3pemusks6Zlfy2s.jpg",
        cast_id: 14,
        character: "Luke Skywalker / Dobbu Scay (voice)",
        credit_id: "5679cdd4c3a3685bbf000206",
        order: 0,
      },
      {
        adult: false,
        gender: 1,
        id: 4,
        known_for_department: "Acting",
        name: "Carrie Fisher",
        original_name: "Carrie Fisher",
        popularity: 1.3083,
        profile_path: "/awb4UqzT6meD3JiQlraIzAqcRtH.jpg",
        cast_id: 15,
        character: "Leia Organa",
        credit_id: "567aa394c3a3685bdf00266a",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 1023139,
        known_for_department: "Acting",
        name: "Adam Driver",
        original_name: "Adam Driver",
        popularity: 1.2058,
        profile_path: "/rsjwgpV2OukxOJ9HEiEyf4qu1vR.jpg",
        cast_id: 13,
        character: "Kylo Ren",
        credit_id: "5679cdbd92514106f50001e9",
        order: 2,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 2,
        id: 3402805,
        known_for_department: "Production",
        name: "Maroje Žanetić",
        original_name: "Maroje Žanetić",
        popularity: 0.0538,
        profile_path: null,
        credit_id: "62719747245dbe3381b0070a",
        department: "Production",
        job: "Location Manager",
      },
      {
        adult: false,
        gender: 2,
        id: 1,
        known_for_department: "Directing",
        name: "George Lucas",
        original_name: "George Lucas",
        popularity: 1.1034,
        profile_path: "/mDLDvsx8PaZoEThkBdyaG1JxPdf.jpg",
        credit_id: "52fe4c709251416c7511a87b",
        department: "Writing",
        job: "Characters",
      },
      {
        adult: false,
        gender: 0,
        id: 2151819,
        known_for_department: "Crew",
        name: "Caridad Angus",
        original_name: "Caridad Angus",
        popularity: 0.0382,
        profile_path: null,
        credit_id: "628592cffa78cd2dc5bcdae0",
        department: "Crew",
        job: "Stand In",
      },
    ],
  },
  genre_ids: [28, 12, 14, 878],
  genres: [
    {
      id: 14,
      name: "Fantasy",
    },
    {
      id: 12,
      name: "Adventure",
    },
    {
      id: 878,
      name: "Science Fiction",
    },
    {
      id: 28,
      name: "Action",
    },
  ],
  homepage:
    "https://www.starwars.com/films/star-wars-episode-viii-the-last-jedi",
  id: 181808,
  imdb_id: "tt2527336",
  original_language: "en",
  original_title: "Star Wars: The Last Jedi",
  overview:
    "Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.",
  popularity: 44.208,
  poster_path: "/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg",
  production_companies: [
    {
      id: 1,
      logo_path: "/o86DbpburjxrqAzEDhXZcyE8pDb.png",
      name: "Lucasfilm",
      origin_country: "US",
    },
    {
      id: 11092,
      logo_path: null,
      name: "Ram Bergman Productions",
      origin_country: "US",
    },
    {
      id: 2,
      logo_path: "/wdrCwmRnLFJhEoH8GSfymY85KHT.png",
      name: "Walt Disney Pictures",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "2017-12-13",
  revenue: 1332459537,
  runtime: 152,
  similar: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: null,
        genre_ids: [28, 27, 14],
        id: 1371510,
        original_language: "en",
        original_title: "Darkside Witches II",
        overview:
          "Father Gabriel's team were slaughtered l by Pazuzu and its demons, the village is cursed, and Gabriel himself captured in the underworld. Lucrezia, the strongest of the black witches, is on her way to Rome to destroy the Vatican.",
        popularity: 0.7507,
        poster_path: "/nC5el7q2MPFIdajCfywMnEVXKv0.jpg",
        release_date: "",
        title: "Darkside Witches II",
        video: false,
        vote_average: 0,
        vote_count: 0,
      },
      {
        adult: false,
        backdrop_path: "/iaNoLnnpQb5SNxGc4bkQmdCvEdG.jpg",
        genre_ids: [16, 10751, 35, 14, 12],
        id: 809,
        original_language: "en",
        original_title: "Shrek 2",
        overview:
          "Shrek, Fiona, and Donkey set off to Far, Far Away to meet Fiona's mother and father, the Queen and King. But not everyone is happily ever after. Shrek and the King find it difficult to get along, and there's tension in the marriage. The Fairy Godmother discovers that Fiona has married Shrek instead of her son Prince Charming and plots to destroy their marriage.",
        popularity: 20.0681,
        poster_path: "/2yYP0PQjG8zVqturh1BAqu2Tixl.jpg",
        release_date: "2004-05-19",
        title: "Shrek 2",
        video: false,
        vote_average: 7.3,
        vote_count: 12865,
      },
      {
        adult: false,
        backdrop_path: "/qSNz1G1Ts8fFw6v4Vae4aMAjcY7.jpg",
        genre_ids: [14, 12, 16, 35, 10751],
        id: 810,
        original_language: "en",
        original_title: "Shrek the Third",
        overview:
          "The King of Far Far Away has died and Shrek and Fiona are to become King & Queen. However, Shrek wants to return to his cozy swamp and live in peace and quiet, so when he finds out there is another heir to the throne, they set off to bring him back to rule the kingdom.",
        popularity: 17.1519,
        poster_path: "/n4SexGGQzI26E269tfpa80MZaGV.jpg",
        release_date: "2007-05-17",
        title: "Shrek the Third",
        video: false,
        vote_average: 6.297,
        vote_count: 9381,
      },
    ],
    total_pages: 1,
    total_results: 3,
  },
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
  ],
  status: "Released",
  tagline: "Darkness rises... and light to meet it",
  title: "Star Wars: The Last Jedi",
  video: false,
  vote_average: 7,
  vote_count: 9692,
};

export const SamplePerson = {
  adult: false,
  also_known_as: [
    "Ice Cube Nwa",
    "O'Shea Jackson",
    "Westside Connection",
    "N.W.A.",
    "NWA",
    "ო’ში ჯექსონი (Ice Cube)",
  ],
  biography:
    "O'Shea Jackson Sr., better known by his stage name Ice Cube, (born June 15, 1969) is an American rapper, record producer, and filmmaker. He began his career as a member of the hip-hop group C.I.A. and later joined N.W.A. He is known for his roles in the films “Boyz n the Hood,” “Friday,” and the “Jump Street” series.",
  birthday: "1969-06-15",
  deathday: null,
  gender: 2,
  homepage: "https://icecube.com/",
  id: 9778,
  imdb_id: "nm0001084",
  known_for_department: "Acting",
  name: "Ice Cube",
  place_of_birth: "Los Angeles, California, USA",
  popularity: 1.8138,
  profile_path: "/ymR7Yll7HjL6i6Z3pt435hYi91T.jpg",
};

export const SampleTvShow = {
  adult: false,
  backdrop_path: "/qg8Gv2w0dDL8cMsG2QO2hWp58wy.jpg",
  credits: {
    cast: [
      {
        adult: false,
        gender: 1,
        id: 974169,
        known_for_department: "Acting",
        name: "Jenna Ortega",
        original_name: "Jenna Ortega",
        popularity: 11.9202,
        profile_path: "/cV4x7jNmsGLdKZn5I6xVF3Ltnmg.jpg",
        character: "Wednesday Addams",
        credit_id: "68979464e171af0589e24616",
        order: 1,
      },
      {
        adult: false,
        gender: 2,
        id: 884,
        known_for_department: "Acting",
        name: "Steve Buscemi",
        original_name: "Steve Buscemi",
        popularity: 3.8473,
        profile_path: "/lQKdHMxfYcCBOvwRKBAxPZVNtkg.jpg",
        character: "Barry Dort",
        credit_id: "68927083863455aa96dbf9e3",
        order: 3,
      },
      {
        adult: false,
        gender: 2,
        id: 1911865,
        known_for_department: "Acting",
        name: "Hunter Doohan",
        original_name: "Hunter Doohan",
        popularity: 2.2723,
        profile_path: "/ihno5ut6ha8TaubQFgl5Ozco2K1.jpg",
        character: "Tyler Galpin",
        credit_id: "637e4015a410c800c8839f20",
        order: 5,
      },
    ],
    crew: [
      {
        adult: false,
        gender: 0,
        id: 5212070,
        known_for_department: "Crew",
        name: "Chloe O'Reilly",
        original_name: "Chloe O'Reilly",
        popularity: 0.0552,
        profile_path: null,
        credit_id: "679a9d234448da3d2abd6ec7",
        department: "Directing",
        job: "Assistant Director Trainee",
      },
      {
        adult: false,
        gender: 2,
        id: 1403739,
        known_for_department: "Editing",
        name: "Nick Iannelli",
        original_name: "Nick Iannelli",
        popularity: 0.0495,
        profile_path: null,
        credit_id: "6899209483e4a8e3fc5d128f",
        department: "Production",
        job: "Producer",
      },
      {
        adult: false,
        gender: 1,
        id: 4125331,
        known_for_department: "Production",
        name: "Natalie Testa",
        original_name: "Natalie Testa",
        popularity: 0.1281,
        profile_path: null,
        credit_id: "689920a907456e824e8daa5f",
        department: "Production",
        job: "Co-Producer",
      },
    ],
  },
  created_by: [
    {
      id: 18923,
      credit_id: "602e00776743fa003ce65015",
      name: "Miles Millar",
      original_name: "Miles Millar",
      gender: 2,
      profile_path: "/4phggQUKYg2WMMEy4JW8y6pKEVS.jpg",
    },
    {
      id: 18924,
      credit_id: "602e0072d55697003f5a8765",
      name: "Alfred Gough",
      original_name: "Alfred Gough",
      gender: 2,
      profile_path: "/wZV1hProzjw9oR9HtjILDMn2K6A.jpg",
    },
  ],
  episode_run_time: [],
  first_air_date: "2022-11-23",
  genre_ids: [10765, 9648, 35],
  genres: [
    { id: 10765, name: "Sci-Fi & Fantasy" },
    { id: 9648, name: "Mystery" },
    { id: 35, name: "Comedy" },
  ],
  homepage: "https://www.netflix.com/title/81231974",
  id: 119051,
  in_production: true,
  languages: ["en"],
  last_air_date: "2025-08-06",
  last_episode_to_air: {
    id: 6165595,
    name: "If These Woes Could Talk",
    overview:
      "It's an Addams family investigation as Fester and Thing commit themselves to Wednesday's case. Trying to conceal one secret, Bianca stumbles on another.",
    vote_average: 8.1,
    vote_count: 32,
    air_date: "2025-08-06",
    episode_number: 4,
    episode_type: "mid_season",
    production_code: "",
    runtime: 60,
    season_number: 2,
    show_id: 119051,
    still_path: "/irw76zkymiXrrAyC1ftq8Jomsuh.jpg",
  },
  name: "Wednesday",
  next_episode_to_air: {
    id: 6165596,
    name: "Episode 5",
    overview: "",
    vote_average: 0.0,
    vote_count: 0,
    air_date: "2025-09-03",
    episode_number: 5,
    episode_type: "standard",
    production_code: "",
    runtime: null,
    season_number: 2,
    show_id: 119051,
    still_path: null,
  },
  networks: [
    {
      id: 213,
      logo_path: "/wwemzKWzjKYJFfCeiB57q3r4Bcm.png",
      name: "Netflix",
      origin_country: "",
    },
  ],
  number_of_episodes: 16,
  number_of_seasons: 2,
  origin_country: ["US"],
  original_language: "en",
  original_name: "Wednesday",
  overview:
    "Smart, sarcastic and a little dead inside, Wednesday Addams investigates twisted mysteries while making new friends — and foes — at Nevermore Academy.",
  popularity: 360.4297,
  poster_path: "/36xXlhEpQqVVPuiZhfoQuaY4OlA.jpg",
  production_companies: [
    {
      id: 2230,
      logo_path: "/igOjospzsKQIbpuFCGhoN5F9icS.png",
      name: "MGM Television",
      origin_country: "US",
    },
    {
      id: 20356,
      logo_path: "/awFYFsOyoG3VttUmWvnhgZgXxxh.png",
      name: "Millar Gough Ink",
      origin_country: "US",
    },
    {
      id: 186866,
      logo_path: "/crmJkiAcLftaxF3GoQvRHPs7gyv.png",
      name: "Toluca Pictures",
      origin_country: "US",
    },
    {
      id: 8601,
      logo_path: "/kqubCH3sfBAk4znUj7hjqv8ffgi.png",
      name: "Tim Burton Productions",
      origin_country: "US",
    },
  ],
  production_countries: [
    { iso_3166_1: "US", name: "United States of America" },
  ],
  seasons: [
    {
      air_date: "2022-11-23",
      episode_count: 8,
      id: 182137,
      name: "Season 1",
      overview: "",
      poster_path: "/v9fNsN3WNXObKJjBWkiKMuT3XoR.jpg",
      season_number: 1,
      vote_average: 8.5,
    },
    {
      air_date: "2025-08-06",
      episode_count: 8,
      id: 345672,
      name: "Season 2",
      overview: "",
      poster_path: "/aamw6JjKwTy6bdviyIcFKekSD6x.jpg",
      season_number: 2,
      vote_average: 7.8,
    },
  ],
  similar: {
    page: 1,
    results: [
      {
        adult: false,
        backdrop_path: "/b73DCbaqYICq3yUbBe5vxtbXjTX.jpg",
        genre_ids: [10765, 18, 10751],
        id: 2243,
        origin_country: ["US"],
        original_language: "en",
        original_name: "Touched by an Angel",
        overview:
          "Monica, an angel, is tasked with bringing guidance and messages from God to various people who are at a crossroads in their lives.",
        popularity: 11.607,
        poster_path: "/jiSv0xNx6MGhAFfv05Ov7DgDELJ.jpg",
        first_air_date: "1994-09-21",
        name: "Touched by an Angel",
        vote_average: 7.2,
        vote_count: 174,
      },
    ],
    total_pages: 1,
    total_results: 1,
  },
  spoken_languages: [
    { english_name: "English", iso_639_1: "en", name: "English" },
  ],
  status: "Returning Series",
  tagline: "The wait has been torture.",
  type: "Scripted",
  vote_average: 8.402,
  vote_count: 9504,
};
